### PR TITLE
Improve code quality

### PR DESCRIPTION
**Pull request by iamcarbon**
This PR makes no functional changes and is focused on some minor cleanup.

### CODE REVIEW

**Comment by iamcarbon** [comment]
@theolivenbaum ready for review

**Comment by iamcarbon** [comment]
@theolivenbaum Quick ping on this.

**Comment by theolivenbaum** [comment]
Hi @iamcarbon! 

Thanks for the pull request, can you also just add your contributors' agreement to the pullrequest under .github/contributors/iamcarbon.md? The template is available [here](https://github.com/curiosity-ai/catalyst/blob/master/.github/contributors/TEMPLATE.md).

Cheers,

Rafael

**Comment by iamcarbon** [comment]
@theolivenbaum Oh no. You may want to revisit the terms of the overly broad patent terms that force contributors to give up their rights to ALL their patents (and provide your company with perpetual rights to sublicense for free). Sadly, I'm unable to agree.

:(

-- 

"With respect to any patents you own, or that you can license without payment to any third party, you hereby grant to us a perpetual, irrevocable, non-exclusive, worldwide, no-charge, royalty-free license to:

make, have made, use, sell, offer to sell, import, and otherwise transfer your contribution in whole or in part, alone or in combination with or included in any product, work or materials arising out of the project to which your contribution was submitted, and

at our option, to sublicense these same rights to third parties through multiple levels of sublicensees or other licensing arrangements."

**Comment by theolivenbaum** [comment]
Hi @iamcarbon 

I was actually surprised by your message, because it is a standard contributor agreement that is also used by other projects, such as [spaCy ](https://github.com/explosion/spaCy/tree/master/.github/contributors).

Just to recap:

> With respect to any patents you own, or that you can license without payment to any third party, you hereby grant to us a perpetual, irrevocable, non-exclusive, worldwide, no-charge, royalty-free license to:
> 
> make, have made, use, sell, offer to sell, import, and otherwise transfer **your contribution in whole or in part, alone or in combination with or included in any product, work or materials arising out of the project to which your contribution was submitted**, and
> 
> at our option, to sublicense these same rights to third parties through multiple levels of sublicensees or other licensing arrangements.

I think you're misunderstanding the broadness of this clause. The rights to use the patents only applies in relation to the code contribution you would be submitting - obviously this does not give us any rights to use your patents outside of the scope of the code you would contribute - i.e. if you have a completely unrelated patent to the code you would be contributing...

**Comment by iamcarbon** [comment]
I think you are right (in my misunderstanding). And agree 100% on the intent / purpose of ensuring that related patents rights are granted to projects with contributions. Giving this another read!

**Pull request closed without merging**
